/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "tertiary-container": "#bc5b00",
        "inverse-primary": "#a3c9ff",
        "surface": "#f8f9ff",
        "primary-fixed": "#d3e3ff",
        "on-secondary-container": "#5c636c",
        "background": "#f8f9ff",
        "outline-variant": "#c0c7d4",
        "secondary-fixed": "#dce3ed",
        "secondary-fixed-dim": "#c0c7d1",
        "primary-fixed-dim": "#a3c9ff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9ff",
        "outline": "#717783",
        "on-tertiary-container": "#ffffff",
        "primary-container": "#0078d4",
        "tertiary-fixed-dim": "#ffb689",
        "on-surface": "#181c22",
        "on-secondary-fixed-variant": "#404750",
        "error-container": "#ffdad6",
        "secondary": "#585f68",
        "on-primary-fixed": "#001c39",
        "tertiary": "#974700",
        "secondary-container": "#d9e0eb",
        "surface-container-highest": "#e0e2ea",
        "on-primary-container": "#ffffff",
        "on-surface-variant": "#404752",
        "on-secondary": "#ffffff",
        "surface-dim": "#d7dae2",
        "primary": "#005faa",
        "surface-container": "#ebeef6",
        "inverse-on-surface": "#eef0f9",
        "on-primary-fixed-variant": "#004883",
        "surface-tint": "#0060ab",
        "on-background": "#181c22",
        "surface-container-low": "#f1f3fc",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdbc8",
        "on-secondary-fixed": "#151c24",
        "on-tertiary-fixed-variant": "#743500",
        "on-tertiary-fixed": "#311300",
        "surface-variant": "#e0e2ea",
        "inverse-surface": "#2d3137",
        "surface-container-high": "#e6e8f0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "lg": "24px",
        "margin": "24px",
        "xl": "32px",
        "md": "16px",
        "xs": "4px",
        "base": "4px",
        "gutter": "16px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-id": ["JetBrains Mono", "monospace"],
        "metadata": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "h1-mobile": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
