import React, { useEffect, useState } from 'react';
import { reportApi } from '../../services/reportApi';
import { projectApi } from '../../services/projectApi';
import { FileText, Plus, Loader2, RefreshCw } from 'lucide-react';
import { useWebSocket } from '../../hooks/useWebSocket';

const StatusBadge = ({ status }: { status: string }) => {
  const map: Record<string, string> = {
    COMPLETED: 'bg-green-100 text-green-700',
    FAILED: 'bg-error-container text-error',
    QUEUED: 'bg-surface-container text-on-surface-variant',
    PROCESSING: 'bg-blue-100 text-blue-700',
  };
  return <span className={`px-sm py-[2px] rounded-full text-label-md font-label-md ${map[status] || ''}`}>{status}</span>;
};

export const Reports: React.FC = () => {
  const [reports, setReports] = useState<any[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ projectId: '', type: 'PROJECT_SUMMARY' });
  const [generating, setGenerating] = useState(false);
  const { connected, subscribe } = useWebSocket();

  const load = async () => {
    try {
      const [rRes, pRes] = await Promise.all([reportApi.getAll(), projectApi.getAll()]);
      setReports(rRes.data);
      setProjects(pRes.data);
    } catch {} finally { setLoading(false); }
  };

  useEffect(() => { load(); }, []);

  useEffect(() => {
    if (connected) {
      subscribe('/topic/jobs', (updatedJob) => {
        setReports(prev => prev.map(r => 
          r.job?.id === updatedJob.id ? { ...r, job: updatedJob } : r
        ));
      });
    }
  }, [connected]);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setGenerating(true);
    try {
      await reportApi.generate(Number(form.projectId), form.type);
      setShowCreate(false);
      await load();
    } catch {} finally { setGenerating(false); }
  };

  return (
    <div className="p-lg h-full overflow-auto">
      <div className="flex items-center justify-between mb-lg">
        <div>
          <h1 className="font-h1 text-h1 font-bold text-on-surface">Reports</h1>
          <p className="text-on-surface-variant font-body-sm flex items-center gap-2">
            Async project reports generated by background workers
            {connected ? (
               <span className="text-green-600 text-xs flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span> Live</span>
            ) : (
               <span className="text-outline text-xs">Offline</span>
            )}
          </p>
        </div>
        <div className="flex gap-sm">
          <button onClick={load} className="flex items-center gap-xs border border-outline-variant px-md py-sm rounded-lg hover:bg-surface-container transition-colors text-label-md">
            <RefreshCw size={14} /> Refresh
          </button>
          <button onClick={() => setShowCreate(true)}
            className="flex items-center gap-xs bg-primary text-on-primary px-md py-sm rounded-lg text-label-md hover:bg-primary/90 transition-colors">
            <Plus size={16} /> Generate Report
          </button>
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center py-xl"><Loader2 size={32} className="animate-spin text-primary" /></div>
      ) : reports.length === 0 ? (
        <div className="text-center py-2xl border-2 border-dashed border-outline-variant rounded-xl">
          <FileText size={48} className="mx-auto text-on-surface-variant opacity-30 mb-sm" />
          <p className="font-label-lg text-on-surface-variant">No reports yet</p>
          <p className="text-on-surface-variant font-body-sm mt-xs">Generate a report to see analytics for your projects.</p>
        </div>
      ) : (
        <div className="space-y-sm">
          {reports.map((r: any) => (
            <div key={r.id} className="bg-surface-container-lowest rounded-xl border border-outline-variant p-md flex items-center gap-md">
              <div className="w-10 h-10 rounded-lg bg-primary-container text-on-primary-container flex items-center justify-center">
                <FileText size={18} />
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-label-md font-semibold text-on-surface">{r.type} Report</p>
                <p className="font-body-sm text-on-surface-variant">
                  Project #{r.project?.id} · {new Date(r.createdAt).toLocaleString()}
                </p>
              </div>
              <StatusBadge status={r.job?.status || 'UNKNOWN'} />
              {r.content && (
                <button onClick={() => alert(r.content)} className="text-primary hover:underline font-label-md text-sm">
                  View
                </button>
              )}
            </div>
          ))}
        </div>
      )}

      {showCreate && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50">
          <div className="bg-surface-container-lowest rounded-xl border border-outline-variant shadow-xl w-[420px] p-xl">
            <h2 className="font-h2 font-bold text-on-surface mb-lg">Generate Report</h2>
            <form onSubmit={handleGenerate} className="space-y-md">
              <div>
                <label className="block font-label-md text-on-surface mb-xs">Project</label>
                <select value={form.projectId} onChange={e => setForm(f => ({ ...f, projectId: e.target.value }))}
                  required className="w-full px-sm py-[8px] border border-outline-variant rounded-md text-body-sm focus:border-primary focus:outline-none">
                  <option value="">Select project...</option>
                  {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                </select>
              </div>
              <div>
                <label className="block font-label-md text-on-surface mb-xs">Report Type</label>
                <select value={form.type} onChange={e => setForm(f => ({ ...f, type: e.target.value }))}
                  className="w-full px-sm py-[8px] border border-outline-variant rounded-md text-body-sm focus:border-primary focus:outline-none">
                  <option value="PROJECT_SUMMARY">Project Summary</option>
                  <option value="TASK_ANALYSIS">Task Analysis</option>
                </select>
              </div>
              <div className="flex gap-sm pt-sm">
                <button type="button" onClick={() => setShowCreate(false)}
                  className="flex-1 py-sm border border-outline-variant rounded-lg hover:bg-surface-container transition-colors">
                  Cancel
                </button>
                <button type="submit" disabled={generating}
                  className="flex-1 py-sm bg-primary text-on-primary rounded-lg hover:bg-primary/90 disabled:opacity-70 flex items-center justify-center gap-xs">
                  {generating && <Loader2 size={14} className="animate-spin" />}
                  Generate
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
